name = "steps-livekit-vendor-proxy"
main = "worker.js"
compatibility_date = "2024-11-20"

routes = [
  { pattern = "https://steps-presinter-cam.pages.dev/vendor/livekit-client.umd.js", custom_domain = false }
]
