name = "lk-token"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
LIVEKIT_API_KEY = "APIL7uQa7GDF5Kb"
LIVEKIT_API_SECRET = "hCMtggFOUHGyJghlxfAm2dHGYwwqEQjBxmFxpqlNjka"
LIVEKIT_URL = "wss://presinter-stream-gjthpz2z.livekit.cloud"
